[all]
deps=["udhr-ph.md", "metric", "distance"]

[metric]
deps=["english.txt", "inglish.txt"]
exec="expr 1000 \* $(diff -w $+ | wc -l) / \( 2 \* $(wc -l <english.txt) \)"

[diff]
deps=["english.txt", "inglish.txt"]
exec="sdiff --width=50 --ignore-all-space $+ || true"

["udhr-ph.md"]
deps=["udhr.md", "site/phonetic.js"]
exec="node convert.js <$< >$@"

["phonetic.txt"]
deps=["cmudict-0.7b.txt", "BUILD.toml"]
exec="""
sed <$< >$@ '
/;;;.*$/d
/^[^A-Z]/d
s/  AA1/ o/g	                # /ɑ/~/ɒ/ long vowel -- BATH, PALM, START -- fast, half, car
s/ AA0/o/g	                # /ɑ/~/ɒ/ long vowel -- BATH, PALM, START -- fast, half, car
s/ AA1/a/g	                # /ɑ/~/ɒ/ long vowel -- BATH, PALM, START -- fast, half, car
s/ AA2/o/g	                # /ɑ/~/ɒ/ long vowel -- BATH, PALM, START -- fast, half, car
s/ AE[012]/a/g	            # /æ/ short vowel -- TRAP, BATH -- cat, fast, pass
s/ AH1 V/of/g	            # /ʌ/ short vowel primary stress initial -- STRUT -- son, courage, blood
s/  AH0/ a/g	                # /ʌ/ short vowel no stress final -- STRUT -- son, courage, blood
s/ AH0$/e/g	                # /ʌ/ short vowel no stress final -- STRUT -- son, courage, blood
s/ AH0/a/g	                # /ʌ/ short vowel no stress -- STRUT -- son, courage, blood
s/ AH1/u/g	                # /ʌ/ short vowel primary stress -- STRUT -- son, courage, blood
s/ AH2/o/g	                # /ʌ/ short vowel secondary stress -- STRUT -- son, courage, blood
s/ AO0/o/g	                # /ɔ/ long vowel no stress -- THOUGHT, NORTH, CURE -- water, four, sure
s/ AO1$/aw/g	                # /ɔ/ long vowel primary stress -- THOUGHT, NORTH, CURE -- water, four, sure
s/  AO1/ o/g	                # /ɔ/ long vowel primary stress -- THOUGHT, NORTH, CURE -- water, four, sure
s/ AO1/o/g	                # /ɔ/ long vowel primary stress -- THOUGHT, NORTH, CURE -- water, four, sure
s/ AO2/a/g	                # /ɔ/ long vowel secondary stress -- THOUGHT, NORTH, CURE -- water, four, sure
s/ AW[012]/ou/g	            # /aʊ/ diphthong vowel -- MOUTH -- noun, cow, shower
s/ AY[012]$/y/g	            # /aɪ/ diphthong vowel final -- PRICE -- try, night, height
s/ AY[012]/i/g	            # /aɪ/ vowel not final -- PRICE -- try, night, height
s/ B/b/g	                # /b/ stop
s/ CH/ch/g	                # /tʃ/ affricate
s/ DH/th/g	                # /ð/ fricative
s/ D/d/g	                # /d/ stop
s/ EH[012]/e/g	            # /ɛ/ short vowel -- DRESS -- bread, many, friend
s/ ER[012]/er/g	            # /ɝ/ vowel
s/ EY[012]$/ay/g	        # /eɪ/ diphthong vowel final -- FACE -- say, stain, freight
s/ EY[012]/ai/g	            # /eɪ/ diphthong vowel not final -- FACE -- say, stain, freight
s/ F/f/g	                # /f/ fricative
s/ G/g/g	                # /ɡ/ stop
s/ HH/h/g	                # /h/ aspirate
s/ IH[012]/i/g	            # /ɪ/ short vowel -- KIT -- myth, pretty, women
s/  ([A-Z]) IY1$/ \\\\1y/g	# /i/ long vowel primary stress final -- FLEECE -- sea, people, police
s/ IY0$/y/g	                # /i/ long vowel unstress final -- FLEECE -- sea, people, police
s/ IY1$/e/g	            # /i/ long vowel primary stress final -- FLEECE -- sea, people, police
s/ IY[012]/ee/g	            # /i/ long vowel not final -- FLEECE -- sea, people, police
s/ JH/j/g	                # /dʒ/ affricate
s/ K/c/g	                # /k/ stop
s/ L/l/g	                # /l/ liquid
s/ M/m/g	                # /m/ nasal
s/ NG/ng/g	                # /ŋ/ nasal
s/ N/n/g	                # /n/ nasal
s/ OW[012]/o/g	            # /oʊ/ diphthong vowel -- GOAT -- slow, toe, mauve
s/ OY[012]$/oy/g	        # /ɔɪ/ vowel final
s/ OY[012]/oi/g	            # /ɔɪ/ diphthong vowel not final -- CHOICE -- noise, loiter, boy
s/ P/p/g	                # /p/ stop
s/ R S/rse/g	            # /s/ cluster
s/ R/r/g	                # /ɹ/ liquid
s/ SH/sh/g	                # /ʃ/ fricative
s/ S/s/g	                # /s/ fricative
s/ TH/th/g	                # /θ/ fricative
s/ T/t/g	                # /t/ stop
s/ UH[012]/u/g	            # /ʊ/ short vowel -- FOOT -- took, good, put
s/ UW0/oo/g	            # /u/ long vowel -- GOOSE -- new, due, tuna
s/ UW1/o/g	            # /u/ long vowel -- GOOSE -- new, due, tuna
s/ UW2/oo/g	            # /u/ long vowel -- GOOSE -- new, due, tuna
s/ V/v/g	                # /v/ fricative
s/  W/ w/g	                # /w/ semivowel initial
s/ W/u/g	                # /w/ semivowel non-initial
s/ Y/i/g	                # /j/ semivowel
s/ ZH/s/g	                # /ʒ/ fricative
s/ Z/s/g	                # /z/ fricative
' 
"""

["english.txt"]
deps=["cmudict-0.7b.txt"]
exec="""
sed <$< '
/;;;.*$/d
/^[^A-Z]/d
s/.[1-9].//
' | awk '{print $1}' | tr [:upper:] [:lower:] > $@
"""

["inglish.txt"]
deps=["phonetic.txt"]
exec="""
awk <$< '{print $2}' >$@
"""

["cmudict-0.7b"]
exec="wget https://raw.githubusercontent.com/Alexir/CMUdict/master/cmudict-0.7b"

["cmudict-0.7b.txt"]
deps=["cmudict-0.7b"]
exec="sed 's/\r//g' <$< >$@ "

["site/phonetic.js"]
deps=["phonetic.txt"]
exec="""
awk <$< >$@ -f phonetic.awk
"""

["enwiki-2022-08-29.txt"]
exec="wget https://raw.githubusercontent.com/IlyaSemenov/wikipedia-word-frequency/master/results/enwiki-2022-08-29.txt"

[distance]
deps=["enwiki-2022-08-29.txt", "distance.js", "site/phonetic.js", "BUILD.toml"]
exec="node distance.js $<"

[clean]
exec="rm -f site/phonetic.js cmudict-0.7b.txt inglish.txt phonetic.txt udhr-ph.md"