[website]
# Nothing to do

[import]
exec = """
cd site
rm -f phonate.js phonetic.js
wget https://cdn.jsdelivr.net/npm/phonate/phonate.js
wget https://cdn.jsdelivr.net/npm/phonate/phonetic.js
"""

[dev]
exec = "cp ../phonate/phonate.js ../phonate/phonetic.js site"
