[all]
deps=["udhr-ph.md", "metric"]

[metric]
deps=["english.txt", "inglish.txt"]
exec="expr 1000 \* $(diff -w $+ | wc -l) / \( 2 \* $(wc -l <english.txt) \)"

[diff]
deps=["english.txt", "inglish.txt"]
exec="sdiff --width=50 --ignore-all-space $+ || true"

["udhr-ph.md"]
deps=["udhr.md", "phonetic.js"]
exec="node phonate.js <$< >$@"

["phonetic.txt"]
deps=["cmudict-0.7b.txt", "BUILD.toml"]
exec="""
sed <$< >$@ '
/;;;.*$/d
/^[^A-Z]/d
s/ AA0/o/g	    # ɑ~ɒ vowel
s/ AA1/a/g	    # ɑ~ɒ vowel
s/ AA2/o/g	    # ɑ~ɒ vowel
s/ AE[012]/a/g	    # æ vowel 
s/ AH1 V/ov/g	        # ʌ vowel primary stress initial
s/ AH0/a/g	        # ʌ vowel no stress
s/ AH1/u/g	        # ʌ vowel primary stress
s/ AH2/o/g	        # ʌ vowel secondary stress
s/ AO0/o/g	        # ɔ vowel no stress
s/ AO1/aw/g	        # ɔ vowel primary stress
s/ AO2/a/g	        # ɔ vowel secondary stress
s/ AW[012]/ou/g	    # aʊ vowel
s/ AY[012]$/y/g	    # aɪ vowel final
s/ AY[012]/i/g	    # aɪ vowel not final
s/ B/b/g	        # b stop
s/ CH/ch/g	        # tʃ affricate
s/ DH/th/g	        # ð fricative
s/ D/d/g	        # d stop
s/ EH[012]/e/g	    # ɛ vowel
s/ ER[012]/er/g	    # ɝ vowel
s/ EY[012]$/ay/g	# eɪ vowel final
s/ EY[012]/ai/g	    # eɪ vowel not final
s/ F/f/g	        # f fricative
s/ G/g/g	        # ɡ stop
s/ HH/h/g	        # h aspirate
s/ IH[012]/i/g	    # ɪ vowel
s/  ([A-Z]) IY1$/ \\\\1y/g	        # i primary stress vowel final
s/ IY0$/y/g	        # i unstress vowel final
s/ IY1$/ee/g	        # i primary stress vowel final
s/ IY[012]/ee/g	    # i vowel not final
s/ JH/j/g	        # dʒ affricate
s/ K/k/g	        # k stop
s/ L/l/g	        # l liquid
s/ M/m/g	        # m nasal
s/ NG/ng/g	        # ŋ nasal
s/ N/n/g	        # n nasal
s/ OW[012]/o/g	    # oʊ vowel
s/ OY[012]$/oy/g	# ɔɪ vowel final
s/ OY[012]/oi/g	    # ɔɪ vowel not final
s/ P/p/g	        # p stop
s/ R S/rse/g	    # s cluster
s/ R/r/g	        # ɹ liquid
s/ SH/sh/g	        # ʃ fricative
s/ S/s/g	        # s fricative
s/ TH/th/g	        # θ fricative
s/ T/t/g	        # t stop
s/ UH[012]/u/g	    # ʊ vowel
s/ UW[012]/oo/g	    # u vowel
s/ V/v/g	        # v fricative
s/  W/ w/g	        # w semivowel initial
s/ W/u/g	        # w semivowel non-initial
s/ Y/i/g	        # j semivowel
s/ ZH/s/g	        # ʒ fricative
s/ Z/s/g	        # z fricative
' 
"""

["english.txt"]
deps=["cmudict-0.7b.txt"]
exec="""
sed <$< '
/;;;.*$/d
/^[^A-Z]/d
s/.[1-9].//
' | awk '{print $1}' | tr [:upper:] [:lower:] > $@
"""

["inglish.txt"]
deps=["phonetic.txt"]
exec="""
awk <$< '{print $2}' >$@
"""

["cmudict-0.7b"]
exec="wget https://raw.githubusercontent.com/Alexir/CMUdict/master/cmudict-0.7b"

["cmudict-0.7b.txt"]
deps=["cmudict-0.7b"]
exec="sed 's/\r//g' <$< >$@ "

["phonetic.js"]
deps=["phonetic.txt"]
exec="""
awk <$< >$@ '
BEGIN {
    print "export default {"
} 
$1 ~ /^[A-Z][A-Z]*$/ {
    print $1 ": \\"" $2 "\\","
}
END {
    print "};"
}
'
"""