[all]
deps=["udhr-ph.md", "metric"]

[metric]
deps=["english.txt", "inglish.txt"]
exec="expr 100 \* $(diff -w $+ | wc -l) / \( 2 \* $(wc -l <english.txt) \)"

[diff]
deps=["english.txt", "inglish.txt"]
exec="sdiff --width=50 --ignore-all-space $+ || true"

["udhr-ph.md"]
deps=["udhr.md", "phonetic.js"]
exec="node phonate.js <$< >$@"

["phonetic.txt"]
deps=["cmudict-0.7b.txt", "BUILD.toml"]
exec="""
sed <$< >$@ '
/;;;.*$/d
/^[^A-Z]/d
s/ N Y/ñ/g
s/ AA[012]/o/g	#vowel
s/ AE[012]/a/g	#vowel
s/ AH0/a/g	#vowel no stress
s/ AH1/o/g	#vowel primary stress
s/ AH2/o/g	#vowel secondary stress
s/ AO0/o/g	#vowel no stress
s/ AO1/oa/g	#vowel primary stress
s/ AO2/a/g	#vowel secondary stress
s/ AW[012]/a/g	#vowel
s/ AY[012]/i/g	#vowel
s/ B/b/g	#stop
s/ CH/ch/g	#affricate
s/ DH/th/g	#fricative
s/ D/d/g	#stop
s/ EH[012]/e/g	#vowel
s/ ER[012]/e/g	#vowel
s/ EY[012]/ay/g	#vowel
s/ F/f/g	#fricative
s/ G/g/g	#stop
s/ HH/h/g	#aspirate
s/ IH[012]/i/g	#vowel
s/ IY[012]$/y/g	#vowel
s/ IY[012]/ee/g	#vowel
s/ JH/j/g	#affricate
s/ K/k/g	#stop
s/ L/l/g	#liquid
s/ M/m/g	#nasal
s/ NG/ng/g	#nasal
s/ N/n/g	#nasal
s/ OW[012]/o/g	#vowel
s/ OY[012]/oi/g	#vowel
s/ P/p/g	#stop
s/ R/r/g	#liquid
s/ SH/sh/g	#fricative
s/ S/s/g	#fricative
s/ TH/th/g	#fricative
s/ T/t/g	#stop
s/ UH[012]/u/g	#vowel
s/ UW[012]/oo/g	#vowel
s/ V/v/g	#fricative
s/ W/w/g	#semivowel
s/ Y/i/g	#semivowel
s/ ZH/s/g	#fricative
s/ Z/s/g	#fricative
' 
"""

["english.txt"]
deps=["cmudict-0.7b.txt"]
exec="""
sed <$< '
/;;;.*$/d
/^[^A-Z]/d
s/.[1-9].//
' | awk '{print $1}' | tr [:upper:] [:lower:] > $@
"""

["inglish.txt"]
deps=["phonetic.txt"]
exec="""
awk <$< '{print $2}' >$@
"""

["cmudict-0.7b"]
exec="wget https://raw.githubusercontent.com/Alexir/CMUdict/master/cmudict-0.7b"

["cmudict-0.7b.txt"]
deps=["cmudict-0.7b"]
exec="sed 's/\r//g' <$< >$@ "

["phonetic.js"]
deps=["phonetic.txt"]
exec="""
awk <$< >$@ '
BEGIN {
    print "export default {"
} 
$1 ~ /^[A-Z][A-Z]*$/ {
    print $1 ": \\"" $2 "\\","
}
END {
    print "};"
}
'
"""