[all]
deps=["udhr-ph.md", "metric"]

[metric]
deps=["english.txt", "inglish.txt"]
exec="expr 100 \* $(diff -w $+ | wc -l) / \( 2 \* $(wc -l <english.txt) \)"

[diff]
deps=["english.txt", "inglish.txt"]
exec="sdiff --width=50 --ignore-all-space $+ || true"

["udhr-ph.md"]
deps=["udhr.md", "phonetic.js"]
exec="node phonate.js <$< >$@"

["phonetic.txt"]
deps=["cmudict-0.7b.txt", "BUILD.toml"]
exec="""
sed <$< >$@ '
/;;;.*$/d
/^[^A-Z]/d
s/ N Y/ñ/g
s/ AA[012]*/o/g	#vowel
s/ AE[012]*/a/g	#vowel
s/ AH0/a/g	#vowel no stress
s/ AH1/o/g	#vowel primary stress
s/ AH2/o/g	#vowel secondary stress
s/ AO[012]*/oa/g	#vowel
s/ AW[012]*/a/g	#vowel
s/ AY[012]*/i/g	#vowel
s/ B[012]*/b/g	#stop
s/ CH[012]*/ch/g	#affricate
s/ DH[012]*/th/g	#fricative
s/ D[012]*/d/g	#stop
s/ EH[012]*/e/g	#vowel
s/ ER[012]*/e/g	#vowel
s/ EY[012]*/ay/g	#vowel
s/ F[012]*/f/g	#fricative
s/ G[012]*/g/g	#stop
s/ HH[012]*/h/g	#aspirate
s/ IH[012]*/i/g	#vowel
s/ IY[012]*/ee/g	#vowel
s/ JH[012]*/j/g	#affricate
s/ K[012]*/k/g	#stop
s/ L[012]*/l/g	#liquid
s/ M[012]*/m/g	#nasal
s/ NG[012]*/ng/g	#nasal
s/ N[012]*/n/g	#nasal
s/ OW[012]*/o/g	#vowel
s/ OY[012]*/oi/g	#vowel
s/ P[012]*/p/g	#stop
s/ R[012]*/r/g	#liquid
s/ SH[012]*/sh/g	#fricative
s/ S[012]*/s/g	#fricative
s/ TH[012]*/th/g	#fricative
s/ T[012]*/t/g	#stop
s/ UH[012]*/u/g	#vowel
s/ UW[012]*/oo/g	#vowel
s/ V[012]*/v/g	#fricative
s/ W[012]*/w/g	#semivowel
s/ Y[012]*/i/g	#semivowel
s/ ZH[012]*/s/g	#fricative
s/ Z[012]*/s/g	#fricative
' 
"""

["english.txt"]
deps=["cmudict-0.7b.txt"]
exec="""
sed <$< '
/;;;.*$/d
/^[^A-Z]/d
s/.[1-9].//
' | awk '{print $1}' | tr [:upper:] [:lower:] > $@
"""

["inglish.txt"]
deps=["phonetic.txt"]
exec="""
awk <$< '{print $2}' >$@
"""

["cmudict-0.7b"]
exec="wget https://raw.githubusercontent.com/Alexir/CMUdict/master/cmudict-0.7b"

["cmudict-0.7b.txt"]
deps=["cmudict-0.7b"]
exec="sed 's/\r//g' <$< >$@ "

["phonetic.js"]
deps=["phonetic.txt"]
exec="""
awk <$< >$@ '
BEGIN {
    print "export default {"
} 
$1 ~ /^[A-Z][A-Z]*$/ {
    print $1 ": \\"" $2 "\\","
}
END {
    print "};"
}
'
"""